<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Okay</name>
   <tag></tag>
   <elementGuidId>c9f63790-6558-43da-b768-be3b0620ad2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button._148dgdpk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[148]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1a43c24b-7349-4364-840a-c1fcf5749f28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5cb54cc1-d733-4846-ac87-8785e8271186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_148dgdpk</value>
      <webElementGuid>7515f2e1-721c-43a1-acb3-c62bf5ff7cdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Okay</value>
      <webElementGuid>48933fdd-5a2a-43f2-8416-c357d28a73fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;scrollbar-gutter js-focus-visible&quot;]/body[@class=&quot;with-new-header&quot;]/div[5]/div[1]/div[@class=&quot;t1bgcr6e&quot;]/div[1]/div[1]/div[1]/div[@class=&quot;_153hgp9&quot;]/section[@class=&quot;_1dl71rl&quot;]/div[@class=&quot;_gsw2t0&quot;]/div[@class=&quot;_160gnkxa&quot;]/button[@class=&quot;_148dgdpk&quot;]</value>
      <webElementGuid>cd878087-eca6-48d6-917a-7c9acbb2956a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[148]</value>
      <webElementGuid>d656825d-8284-4182-9c2e-be74d96f0d54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cookie-Einstellungen'])[1]/following::button[1]</value>
      <webElementGuid>585f1f29-a1d3-47d2-8fd2-f63cdb85c1a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cookie-Richtlinie'])[1]/following::button[2]</value>
      <webElementGuid>37391321-e1e6-4634-986a-c9a9e5b80fcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div[2]/div[2]/button</value>
      <webElementGuid>245f5b82-3349-446f-9c06-f5016f2500c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Okay' or . = 'Okay')]</value>
      <webElementGuid>fb5fe19c-5bc5-4dc5-9a42-50f2c893648b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
