<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Mit Aussicht_i1wps9q8 dir dir-ltr</name>
   <tag></tag>
   <elementGuidId>74fca226-6101-4896-a692-8774b0fc0662</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='categoryScroller']/div/div/div/div/div/div/div[3]/div/div/div/div/button[6]/div/span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>239691b9-5010-4404-bfd4-4c753a9e0d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>i1wps9q8 dir dir-ltr</value>
      <webElementGuid>8ceda769-5f9f-4917-94f7-6a1121f888fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://a0.muscache.com/pictures/8e507f16-4943-4be9-b707-59bd38d56309.jpg</value>
      <webElementGuid>0674e6c1-6ffb-49ed-bd04-c4cb351674f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>a5d67b64-d920-4ba2-be3c-73c81736cc4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>18a1a906-be91-40f7-b349-6d939ef21cc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;categoryScroller&quot;)/div[@class=&quot;c1yfmptw clu53zf dir dir-ltr&quot;]/div[@class=&quot;e13keydh e1gc5f0n dir dir-ltr&quot;]/div[@class=&quot;s1in1q3d dir dir-ltr&quot;]/div[@class=&quot;cbdpsi8 dir dir-ltr&quot;]/div[1]/div[@class=&quot;rztl681 dir dir-ltr&quot;]/div[@class=&quot;s1yvqyx7 dir dir-ltr&quot;]/div[@class=&quot;dir dir-ltr&quot;]/div[@class=&quot;awuxh4x dir dir-ltr&quot;]/div[@class=&quot;cw9aemg dir dir-ltr&quot;]/div[@class=&quot;c14whb16 dir dir-ltr&quot;]/button[@class=&quot;c1l3w0tx dir dir-ltr&quot;]/div[@class=&quot;c8gkmzg dir dir-ltr&quot;]/span[@class=&quot;c1m2z0bj dir dir-ltr&quot;]/img[@class=&quot;i1wps9q8 dir dir-ltr&quot;]</value>
      <webElementGuid>5a9e3465-ba4f-4f69-8c7b-46745a8afab7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='categoryScroller']/div/div/div/div/div/div/div[3]/div/div/div/div/button[6]/div/span/img</value>
      <webElementGuid>fd5350d7-86a6-433c-ad75-897220be7c96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://a0.muscache.com/pictures/8e507f16-4943-4be9-b707-59bd38d56309.jpg')]</value>
      <webElementGuid>0db3d251-ed2f-45ba-936f-df6d692b79f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[6]/div/span/img</value>
      <webElementGuid>61660447-d72c-43d1-afe0-3c83b69b6912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://a0.muscache.com/pictures/8e507f16-4943-4be9-b707-59bd38d56309.jpg']</value>
      <webElementGuid>b19da88c-e372-42cf-b524-e07a0d60676a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
