<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Wer__kaq6tx</name>
   <tag></tag>
   <elementGuidId>e6ad879a-a117-4df6-bf01-be43dd641016</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span._kaq6tx</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='search-tabpanel']/div/div[5]/div/div[2]/button/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>21746cb6-33fb-488d-accf-50a4d3f02a82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_kaq6tx</value>
      <webElementGuid>8ba1418d-d998-453d-b34a-700266339f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-tabpanel&quot;)/div[@class=&quot;i1wnljx3 dir dir-ltr&quot;]/div[@class=&quot;c6ezw63 c1geg2ah dir dir-ltr&quot;]/div[@class=&quot;c2frgdd crbzydf dir dir-ltr&quot;]/div[@class=&quot;s1i622mb dir dir-ltr&quot;]/button[@class=&quot;b134py57 b14gupvm dir dir-ltr&quot;]/span[@class=&quot;_jxxpcd&quot;]/span[@class=&quot;_kaq6tx&quot;]</value>
      <webElementGuid>dbd8609a-06e1-4a0e-a19c-bb751ad08ada</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search-tabpanel']/div/div[5]/div/div[2]/button/span/span</value>
      <webElementGuid>0e7fbe58-76a4-47c8-8744-4d099c2332ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>084dd6aa-83e4-4936-8440-4639f8a537bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
