<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Preisaufschlsselung anzeigen_FMP-target</name>
   <tag></tag>
   <elementGuidId>e4fe8a06-b013-4e81-b626-c0b6a4bb58ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//img[@id='FMP-target'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5fd6366e-633d-432d-9475-ffc9245521e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_6tbg2q</value>
      <webElementGuid>97942eb8-2e56-448e-8e66-4ee9c0ec44e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0c0873a7-b97f-415f-a125-ad1ce65027d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Image 1</value>
      <webElementGuid>6fa2d8d9-820d-4fc0-8c58-b4eb0e61b63d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>elementtiming</name>
      <type>Main</type>
      <value>LCP-target</value>
      <webElementGuid>ac910a1b-0aa4-4968-b402-67efa9745909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fetchpriority</name>
      <type>Main</type>
      <value>high</value>
      <webElementGuid>ee11b31d-51f3-4b4f-b709-46fb0dcfc200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FMP-target</value>
      <webElementGuid>8ed9574c-4b22-458a-b2ca-d14a49b3c022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>eager</value>
      <webElementGuid>1927af4e-01ad-4814-92ad-5760f81f6b5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://a0.muscache.com/im/pictures/75a7bab2-41a7-48a1-8fbb-2e4ae913c124.jpg?im_w=720</value>
      <webElementGuid>282d81e9-a21c-40e3-9614-6681316a2829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-uri</name>
      <type>Main</type>
      <value>https://a0.muscache.com/im/pictures/75a7bab2-41a7-48a1-8fbb-2e4ae913c124.jpg?im_w=720</value>
      <webElementGuid>7c08d372-04b8-47b6-8670-4edacaab742a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-content&quot;)/div[@class=&quot;f15dgkuj dir dir-ltr&quot;]/div[@class=&quot;aoez2dw dir dir-ltr&quot;]/div[2]/div[@class=&quot;_11ry7lz&quot;]/div[@class=&quot;_19waq6b&quot;]/div[@class=&quot;c1yo0219 dir dir-ltr&quot;]/div[1]/div[@class=&quot;c61fd4t c1885bm1 dir dir-ltr&quot;]/div[@class=&quot;gh7uyir g1xypvzw g14v8520 dir dir-ltr&quot;]/div[@class=&quot;c4mnd7m dir dir-ltr&quot;]/div[@class=&quot;c1l1h97y dir dir-ltr&quot;]/div[1]/div[1]/div[1]/div[@class=&quot;cy5jw6o  dir dir-ltr&quot;]/div[@class=&quot;mz543g6 dir dir-ltr&quot;]/div[@class=&quot;c14dgvke dir dir-ltr&quot;]/div[@class=&quot;cnjlbcx cp0pqp0 rztl681 dir dir-ltr&quot;]/div[@class=&quot;s1yvqyx7 dir dir-ltr&quot;]/div[@class=&quot;dir dir-ltr&quot;]/div[@class=&quot;awuxh4x dir dir-ltr&quot;]/div[@class=&quot;cw9aemg dir dir-ltr&quot;]/div[@class=&quot;c14whb16 dir dir-ltr&quot;]/a[@class=&quot;rfexzly dir dir-ltr&quot;]/div[@class=&quot;cjv59qb dir dir-ltr&quot;]/div[@class=&quot;_1h6n1zu&quot;]/picture[1]/img[@id=&quot;FMP-target&quot;]</value>
      <webElementGuid>1caa815e-801f-4337-84d9-4f371e202c6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//img[@id='FMP-target'])[2]</value>
      <webElementGuid>ca91611e-7cc7-47cb-ad2e-5fa8ca2325e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='site-content']/div[2]/div[3]/div[2]/div/div/div/div/div/div/div[2]/div[2]/div/div/div/div/div/div/div/div[3]/div/div/div/div/a/div/div/picture/img</value>
      <webElementGuid>a38020a9-70f3-4503-b6e0-5d191d1154fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Image 1'])[2]</value>
      <webElementGuid>c1d98f20-53b1-4576-995a-a966b25a2cd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div/div/div/div[3]/div/div/div/div/a/div/div/picture/img</value>
      <webElementGuid>f65122c8-fe17-4a4a-8f3a-bc53b5e03e6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Image 1' and @id = 'FMP-target' and @src = 'https://a0.muscache.com/im/pictures/75a7bab2-41a7-48a1-8fbb-2e4ae913c124.jpg?im_w=720']</value>
      <webElementGuid>01bab7dc-df68-4b14-ad9d-d39429865cd0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
